name       : qsynth
version    : 0.9.11
release    : 10
source     :
    - https://github.com/rncbc/qsynth/archive/qsynth_0_9_11.tar.gz : 716142ee5a587baf3438e0039d7cec742ec82cb1c29eafd14ecac0ecb8a28723
homepage   : https://qsynth.sourceforge.io/
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Fluidsynth GUI frontend
description: |
    Qsynth is a fluidsynth GUI front-end application written in C++ around the Qt framework.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Svg)
    - pkgconfig(fluidsynth)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
