name       : qsynth
version    : 0.5.6
release    : 3
source     :
    - https://sourceforge.net/projects/qsynth/files/qsynth/0.5.6/qsynth-0.5.6.tar.gz/download : a6eb404778fad87bb37fa1fb4caf1d80f24a324f9c3a22b669df2f8c94849040
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Fluidsynth GUI frontend
description: |
    Qsynth is a fluidsynth GUI front-end application written in C++ around the Qt framework.
builddeps  :
    - pkgconfig(fluidsynth)
    - pkgconfig(Qt5Help)
rundeps    :
    - fluidsynth
setup      : |
    %configure
    %qmake QMAKE_CFLAGS_ISYSTEM=-I
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
