name       : qsynth
version    : 0.6.1
release    : 6
source     :
    - https://github.com/rncbc/qsynth/archive/qsynth_0_6_1.tar.gz : 6fcae6d676723e3dd98461950db593b6e524bf8cb381c50619b6767872c40567
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Fluidsynth GUI frontend
description: |
    Qsynth is a fluidsynth GUI front-end application written in C++ around the Qt framework.
builddeps  :
    - pkgconfig(fluidsynth)
    - pkgconfig(Qt5Help)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
