name       : qsynth
version    : 0.6.2
release    : 7
source     :
    - https://github.com/rncbc/qsynth/archive/qsynth_0_6_2.tar.gz : b307f168f1ed997f2b964a1ea1256638959b7d278fee5bf03d54806103fb2f0c
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Fluidsynth GUI frontend
description: |
    Qsynth is a fluidsynth GUI front-end application written in C++ around the Qt framework.
builddeps  :
    - pkgconfig(fluidsynth)
    - pkgconfig(Qt5Help)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
