name       : qsynth
version    : 0.6.0
release    : 5
source     :
    - https://github.com/rncbc/qsynth/archive/qsynth_0_6_0.tar.gz : fa82ce459313352d1dbbb44a98774dd966534734a298f58aede7218f21a02221
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Fluidsynth GUI frontend
description: |
    Qsynth is a fluidsynth GUI front-end application written in C++ around the Qt framework.
builddeps  :
    - pkgconfig(fluidsynth)
    - pkgconfig(Qt5Help)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
