name       : qsynth
version    : 0.5.5
release    : 2
source     :
    - https://sourceforge.net/projects/qsynth/files/qsynth/0.5.5/qsynth-0.5.5.tar.gz/download : 858f52b95642a25f570342d5cf7fafd2a2addb89d567c5b68a3545beb6fda723
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Fluidsynth GUI frontend
description: |
    Qsynth is a fluidsynth GUI front-end application written in C++ around the Qt framework.
builddeps  :
    - pkgconfig(fluidsynth)
    - pkgconfig(Qt5Help)
rundeps    :
    - fluidsynth
setup      : |
    %configure
    %qmake QMAKE_CFLAGS_ISYSTEM=-I
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
