name       : qsynth
version    : 0.5.4
release    : 1
source     :
    - https://sourceforge.net/projects/qsynth/files/qsynth/0.5.4/qsynth-0.5.4.tar.gz/download : 2d6befb4023f8a64f35d802991d0d413e11d0307e87485428c969b94bb2bf84e
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Fluidsynth GUI frontend
description: |
    Qsynth is a fluidsynth GUI front-end application written in C++ around the Qt framework.
builddeps  :
    - pkgconfig(fluidsynth)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
rundeps    :
    - fluidsynth
setup      : |
    %configure
    %qmake QMAKE_CFLAGS_ISYSTEM=-I
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
